[project]
name = "hscida"
r_version = "4.6"

repositories = [
    {alias = "hsci", url = "https://hsci-r.r-universe.dev/"},
    {alias = "cloud", url = "https://cloud.r-project.org/"},
]

dependencies = [
    "bit64",
    "DBI",
    "dplyr",
    "duckdb",
    "dotenv",
    "glue",
    "here",
    "readr",
    "rlang",
    "stringr",
    "testthat",
    "tibble",
    "dbplyr",
]
